name: TestCentric.CI

on:
  workflow_call:

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  ContinuousIntegration:
    name: TestCentric Continuous Integration
    runs-on: windows-latest

    env:
        TESTCENTRIC_MYGET_API_KEY: ${{ secrets.TESTCENTRIC_MYGET_API_KEY }}
        TESTCENTRIC_NUGET_API_KEY: ${{ secrets.TESTCENTRIC_NUGET_API_KEY }}
        TESTCENTRIC_CHOCO_API_KEY: ${{ secrets.TESTCENTRIC_CHOCO_API_KEY }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.TESTCENTRIC_GITHUB_ACCESS_TOKEN }}

    steps:
      - name: ⤵️ Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Install dotnet tools
        run: dotnet tool restore

      - name: 🍰 Continuous Integration

        # If you need to get more verbose logging, add the following to the dotnet-cake call:  --verbosity=diagnostic
        run: dotnet cake --target=ContinuousIntegration --configuration=Release
